/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004-2009 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev: 7023 $ $Date: 2008-07-17 11:31:01 -0400 (Thu, 17 Jul 2008) $
 *
 */

#ifndef _OSAL_LOG_H_
#define _OSAL_LOG_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "osal_types.h"
#include "osal_constant.h"
#include "osal_platform.h"

/* Maximum size per log. */
#define OSAL_LOG_SIZE_MAX            2048
#define OSAL_MAX_DIAG_LOG_LENGTH     256
 /*
  * Diagnostic event queue name and its depth.
  */
#define OSAL_DIAG_EVENT_QUEUE_NAME   "diag-event"
#define OSAL_DIAG_EVENT_QUEUE_DEPTH  16

#ifndef OSAL_LOG_DEFAULT_PORT
#define OSAL_LOG_DEFAULT_PORT        7654
#endif

/* Default log priority for all log modules. */
#ifndef OSAL_LOG_OSAL_DEFAULT_PRIORITY
#define OSAL_LOG_OSAL_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_VTSP_DEFAULT_PRIORITY
#define OSAL_LOG_VTSP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_DSP_DEFAULT_PRIORITY
#define OSAL_LOG_DSP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_RTCP_DEFAULT_PRIORITY
#define OSAL_LOG_RTCP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_RPM_DEFAULT_PRIORITY
#define OSAL_LOG_RPM_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_ISI_DEFAULT_PRIORITY
#define OSAL_LOG_ISI_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_ISI_RPC_DEFAULT_PRIORITY
#define OSAL_LOG_ISI_RPC_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_CSM_DEFAULT_PRIORITY
#define OSAL_LOG_CSM_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_MC_DEFAULT_PRIORITY
#define OSAL_LOG_MC_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SAPP_DEFAULT_PRIORITY
#define OSAL_LOG_SAPP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_IAPP_DEFAULT_PRIORITY
#define OSAL_LOG_IAPP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_XCAP_DEFAULT_PRIORITY
#define OSAL_LOG_XCAP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_HTTP_DEFAULT_PRIORITY
#define OSAL_LOG_HTTP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_VAPP_DEFAULT_PRIORITY
#define OSAL_LOG_VAPP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_MM_DEFAULT_PRIORITY
#define OSAL_LOG_MM_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_GBA_DEFAULT_PRIORITY
#define OSAL_LOG_GBA_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_EZXML_DEFAULT_PRIORITY
#define OSAL_LOG_EZXML_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SUPSRV_DEFAULT_PRIORITY
#define OSAL_LOG_SUPSRV_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_VIDEO_DEFAULT_PRIORITY
#define OSAL_LOG_VIDEO_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_TRANS_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_TRANS_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_ENCODE_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_ENCODE_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_DECODE_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_DECODE_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_SDP_ENC_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_SDP_ENC_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_SDP_DEC_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_SDP_DEC_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_MEMORY_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_MEMORY_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_TU_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_TU_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_TRANSPORT_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_TRANSPORT_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_TIMER_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_TIMER_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_CRIT
#endif
#ifndef OSAL_LOG_SIP_GENERAL_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_GENERAL_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_CONFIG_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_CONFIG_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_UA_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_UA_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_SESSION_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_SESSION_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_DIALOG_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_DIALOG_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif
#ifndef OSAL_LOG_SIP_APP_DEFAULT_PRIORITY
#define OSAL_LOG_SIP_APP_DEFAULT_PRIORITY OSAL_LOG_PRIORITY_WARN
#endif

/* Log priority enumeration. */
typedef enum {
    OSAL_LOG_PRIORITY_CRIT,    /* Critical. */
    OSAL_LOG_PRIORITY_ERR,     /* Error. */
    OSAL_LOG_PRIORITY_WARN,    /* Warning. */
    OSAL_LOG_PRIORITY_INFO,    /* Informative. */
    OSAL_LOG_PRIORITY_DEBUG    /* Debug. */
} OSAL_LogPriority;

/* Log module enumeration. */
typedef enum {
    OSAL_LOG_MODULE_NONE = 0,
    OSAL_LOG_MODULE_FIRST,
    OSAL_LOG_MODULE_OSAL = OSAL_LOG_MODULE_FIRST,
    OSAL_LOG_MODULE_DSP,
    OSAL_LOG_MODULE_VTSP,
    OSAL_LOG_MODULE_RTCP,
    OSAL_LOG_MODULE_RPM,
    OSAL_LOG_MODULE_CSM,
    OSAL_LOG_MODULE_ISI,
    OSAL_LOG_MODULE_ISI_RPC,
    OSAL_LOG_MODULE_MC,
    OSAL_LOG_MODULE_SAPP,
    OSAL_LOG_MODULE_IAPP,
    OSAL_LOG_MODULE_XCAP,
    OSAL_LOG_MODULE_HTTP,
    OSAL_LOG_MODULE_VAPP,
    OSAL_LOG_MODULE_MM,
    OSAL_LOG_MODULE_GBA,
    OSAL_LOG_MODULE_EZXML,
    OSAL_LOG_MODULE_SUPSRV,
    OSAL_LOG_MODULE_VIDEO,
    OSAL_LOG_MODULE_SIP_FIRST,
    OSAL_LOG_MODULE_SIP_TRANS = OSAL_LOG_MODULE_SIP_FIRST,
    OSAL_LOG_MODULE_SIP_ENCODE,
    OSAL_LOG_MODULE_SIP_DECODE,
    OSAL_LOG_MODULE_SIP_SDP_ENC,
    OSAL_LOG_MODULE_SIP_SDP_DEC,
    OSAL_LOG_MODULE_SIP_MEMORY,
    OSAL_LOG_MODULE_SIP_TU,
    OSAL_LOG_MODULE_SIP_TRANSPORT,
    OSAL_LOG_MODULE_SIP_TIMER,
    OSAL_LOG_MODULE_SIP_GENERAL,
    OSAL_LOG_MODULE_SIP_CONFIG,
    OSAL_LOG_MODULE_SIP_UA,
    OSAL_LOG_MODULE_SIP_SESSION,
    OSAL_LOG_MODULE_SIP_DIALOG,
    OSAL_LOG_MODULE_SIP_APP,
    OSAL_LOG_MODULE_LAST,
} OSAL_LogModule;

/* OSAL log Macros. */
#define OSAL_LOG_MSG_CRIT(module, fmt, args...) \
        _OSAL_logMsgPriority(module, OSAL_LOG_PRIORITY_CRIT, "%s:%d " fmt, __FILE__, __LINE__, ##args)
#define OSAL_LOG_MSG_ERR(module, fmt, args...) \
        _OSAL_logMsgPriority(module, OSAL_LOG_PRIORITY_ERR, "%s:%d " fmt, __FILE__, __LINE__, ##args)
#define OSAL_LOG_MSG_WARN(module, fmt, args...) \
        _OSAL_logMsgPriority(module, OSAL_LOG_PRIORITY_WARN, "%s:%d " fmt, __FILE__, __LINE__, ##args)
#define OSAL_LOG_MSG_INFO(module, fmt, args...) \
        _OSAL_logMsgPriority(module, OSAL_LOG_PRIORITY_INFO, "%s:%d " fmt, __FILE__, __LINE__, ##args)
#define OSAL_LOG_MSG_DEBUG(module, fmt, args...) \
        _OSAL_logMsgPriority(module, OSAL_LOG_PRIORITY_DEBUG, "%s:%d " fmt, __FILE__, __LINE__, ##args)

/* Should be deprecated. Now only be used inside OSAL module for debugging */
#define OSAL_logMsg(fmt, args...) \
        _OSAL_logMsgPriority(OSAL_LOG_MODULE_OSAL,  OSAL_LOG_PRIORITY_DEBUG, "%s:%d " fmt, __FILE__, __LINE__, ##args)

extern const char *OSAL_logModuleName[];
extern const char *OSAL_logPriorityName[];

/* Log message header struct. */
typedef struct {
    uint32 tvSec;
    uint32 tvUsec;
    uint8  module;
    uint8  priority;
} OSAL_LogHeader;

typedef struct {
    char        message[OSAL_MAX_DIAG_LOG_LENGTH];
    int         msgType;
} OSAL_diagMsg;

OSAL_Status OSAL_logSetDestPort(
    uint16 port);

OSAL_Status OSAL_logSetDestAddr(
    uint32 ipv4);

OSAL_Status OSAL_logMinPriority(
    OSAL_LogModule   module,
    OSAL_LogPriority priority);

OSAL_Status _OSAL_logMsgPriority(
    OSAL_LogModule   module,
    OSAL_LogPriority priority,
    const char      *format_ptr,
    ...);


OSAL_Status OSAL_logPrintf(
    const char *format_ptr,
    ...);

OSAL_Status OSAL_logString(
    char *string_ptr);

int  OSAL_getLogLevel(void);

enum {
    _OSAL_LOG_NONE = 0,
    _OSAL_LOG_ERR  = 1,
    _OSAL_LOG_WARN = 2,
    _OSAL_LOG_INFO = 3,
    _OSAL_LOG_ALL  = 7
};
#ifdef __cplusplus
}
#endif

#endif
