#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_PACKAGE                          144	/*Device.Services.X_ZYXEL_Package.i*/
#define RDM_OID_PACKAGE_INSTALL                  324	/*Device.Services.X_ZYXEL_Package_Install*/
#define RDM_OID_VOICE_SRV                        384	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       492	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1296	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1596	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1656	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1740	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1920	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          2916	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   3048	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4644	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4800	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   4908	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              5088	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              5196	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        5328	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5556	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5808	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  6036	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            6144	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      6228	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6432	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6804	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       6984	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   7356	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7632	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7740	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7848	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    7932	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        8088	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       8220	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9720	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 9876	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            10080	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               10356	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10512	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   11292	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       11928	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     12108	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12504	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12540	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12600	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 12780	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            12864	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 13044	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 13104	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 13188	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        13248	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   13308	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13584	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13644	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   14136	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14460	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_VOICE_VOLTE                      14688	/*Device.Services.VoiceService.i.X_ZYXEL_VOLTE*/
#define RDM_OID_DEV_INFO                         14748	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          15312	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          15468	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                15600	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 15684	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              15768	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        15948	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            16008	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     16452	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               16536	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         16620	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            16752	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     16884	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_DEV_INFO_POWER_STAT              17040	/*Device.DeviceInfo.X_ZYXEL_PowerStatus*/
#define RDM_OID_APP_SUPPORT_INFO                 17124	/*Device.DeviceInfo.AppSupportInformation*/
#define RDM_OID_MGMT_SRV                         17256	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                18996	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 19176	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                19308	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        19344	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  19452	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          19584	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 19692	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             19824	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             20076	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_GATEWAY_INFO                     20232	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             20340	/*Device.Time*/
#define RDM_OID_USR_INTF                         21000	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              21612	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              21744	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      21972	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              22128	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         22236	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      26232	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                26580	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             27072	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        27564	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         27648	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         28140	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             28224	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      28788	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   29304	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             29652	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          29832	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     30012	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           30192	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           30372	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      30552	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       31068	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   31152	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 31188	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   31416	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             31884	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       32184	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            32484	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  32784	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               32820	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         33240	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          33276	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              34176	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         34236	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      34584	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              34812	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         34872	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      35412	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     35904	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         36060	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   36096	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   36396	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              36696	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         36756	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      37320	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              37716	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      37848	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        38412	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      38856	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         39252	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      39576	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    39972	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 40272	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              40668	/*Device.USB*/
#define RDM_OID_USB_INTF                         40752	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    41052	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         41448	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     41676	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                41736	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            41964	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        42480	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        42636	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   42720	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_CELL                             42852	/*Device.Cellular*/
#define RDM_OID_CELL_INTF                        43200	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELL_INTF_USIM                   44244	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELL_INTF_ST                     44592	/*Device.Cellular.Interface.i.Stats*/
#define RDM_OID_CELL_INTF_ZY_BUDGET_CONTROL      44988	/*Device.Cellular.Interface.i.X_ZYXEL_BudgetControl*/
#define RDM_OID_CELL_INTF_ZY_IP_PASS_THRU        45648	/*Device.Cellular.Interface.i.X_ZYXEL_IP_PassThrough*/
#define RDM_OID_CELL_INTF_ZY_UI_WAIT_ST          45804	/*Device.Cellular.Interface.i.X_ZYXEL_UiWaitingState*/
#define RDM_OID_CELL_INTF_ZY_SCC                 45984	/*Device.Cellular.Interface.i.X_ZYXEL_SecondaryComponentCarrier.i*/
#define RDM_OID_CELL_INTF_ZY_PCI_LOCK            46212	/*Device.Cellular.Interface.i.X_ZYXEL_PhyCellIdLock*/
#define RDM_OID_CELL_INTF_ZY_PCI_LOCKED_LIST     46320	/*Device.Cellular.Interface.i.X_ZYXEL_PhyCellIdLock.PhyCellIdLockedList.i*/
#define RDM_OID_CELL_INTF_ZY_NBR_CELL            46404	/*Device.Cellular.Interface.i.X_ZYXEL_NeighbourCell.i*/
#define RDM_OID_CELL_INTF_ZY_NR_NSA              46656	/*Device.Cellular.Interface.i.X_ZYXEL_NewRadioNonStandAlone*/
#define RDM_OID_CELL_INTF_ZY_SMS                 46932	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService*/
#define RDM_OID_CELL_INTF_ZY_SMS_INBOX           47064	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService.Inbox.i*/
#define RDM_OID_CELL_INTF_ZY_SMS_OUTBOX          47244	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService.Outbox.i*/
#define RDM_OID_CELL_INTF_ZY_SMS_STORAGE         47424	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService.Storage*/
#define RDM_OID_CELL_ACCESS_POINT                47532	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_CELL_ZY_GNSS_LOC                 47952	/*Device.Cellular.X_ZYXEL_GNSS_Location*/
#define RDM_OID_CELL_INTF_ZY_RESET_CM            48300	/*Device.Cellular.X_ZYXEL_Reset_CM*/
#define RDM_OID_HPNA                             48360	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        48420	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     49104	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    49500	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          49560	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              49932	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        50160	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         50196	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  50472	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              50676	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     50784	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 50892	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  51528	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 51612	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             51912	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        51972	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     52872	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    53268	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            53376	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              53556	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              54000	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         54060	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      54624	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               55020	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        55176	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    55236	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 55656	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          56172	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              56376	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         56436	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      56976	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               57372	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            57672	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              57828	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         57936	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        57972	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             58152	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    58332	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       58392	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    60108	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        60360	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   61020	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                61416	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            61788	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     62808	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            63036	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      63480	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   63756	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  64008	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   64092	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                64272	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               64404	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           64464	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       64644	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WPS                              64776	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  64884	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          64992	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 65436	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   65880	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_BRIDGING                         66204	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      66480	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 66780	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              67248	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 67644	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             67776	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  67932	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              68760	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        68844	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  69792	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  69828	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   69960	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  70116	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   70200	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               70596	/*Device.IP*/
#define RDM_OID_IP_IFACE                         70848	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 72348	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 72600	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               72972	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    73416	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   73812	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          73968	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   74004	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 74448	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          74772	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  74904	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG                  75372	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             75792	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            76116	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         76632	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          76860	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IP_DIAG_NUT_TCP_DIAG             77184	/*Device.IP.Diagnostics.X_ZYXEL_NUTTCP*/
#define RDM_OID_IPSEC                            77580	/*Device.IPSec*/
#define RDM_OID_IPSEC_STAT                       77952	/*Device.IPSec.Stats*/
#define RDM_OID_IPSEC_FILTER                     78276	/*Device.IPSec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    78840	/*Device.IPSec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       79476	/*Device.IPSec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     79608	/*Device.IPSec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                79740	/*Device.IPSec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    79896	/*Device.IPSec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               80244	/*Device.IPSec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   80472	/*Device.IPSec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           80556	/*Device.IPSec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      80712	/*Device.IPSec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_GRE                              80988	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       81072	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  81708	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 81984	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            82284	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       82512	/*Device.GRE.Filter.i*/
#define RDM_OID_CAPT_PORTAL                      82764	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          82896	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   82956	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            83184	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            83700	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      83976	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             84084	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  84336	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         84420	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               84696	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      84780	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           85080	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  85164	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              85752	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           85884	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      85968	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          86268	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 86352	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              86700	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          87312	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          89436	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         89712	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      90036	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          90600	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     91140	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       91440	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     91620	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            91680	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       91764	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               92664	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               92724	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                92784	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              93084	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       93240	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   93348	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        93624	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    93732	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         93912	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          93948	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   94200	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              94380	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 94656	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 94812	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              95328	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 95652	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  95976	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           96156	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    96216	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  96684	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   96816	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       96972	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  97080	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      97932	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              98064	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           98196	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   98352	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       98436	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                98520	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     98700	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 98808	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           99252	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    99312	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                99756	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           99864	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       99996	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       100104	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  100188	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           101040	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   101220	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 101328	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       101436	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              101520	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV6_RELAY                     101676	/*Device.DHCPv6.Relay*/
#define RDM_OID_DHCPV6_RELAY_INTF_SET            101808	/*Device.DHCPv6.Relay.InterfaceSetting.i*/
#define RDM_OID_IEEE8021X                        102036	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             102096	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        102564	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      102864	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      102948	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             103032	/*Device.Users*/
#define RDM_OID_USRS_USR                         103092	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               103272	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           103332	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        103560	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             103716	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         103752	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    104076	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        104400	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               104508	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    104712	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                104916	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             105096	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        105276	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   105504	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         105588	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   105912	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   106164	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              106320	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  107364	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       107472	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 107820	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        108120	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EXEC_ENV               108228	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        108720	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              109092	/*Device.SoftwareModules.ExecutionUnit*/
#define RDM_OID_SW_MODULE_EXEC_UNIT_EXT          109632	/*Device.SoftwareModules.ExecutionUnit.Extensions*/
#define RDM_OID_FAULT_MGMT                       109668	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            109848	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         110004	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         110280	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       110556	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            110832	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          111108	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     111168	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              111636	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          111672	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         112044	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            112416	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    112644	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               112704	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    112908	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               113064	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               113412	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   113496	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           113724	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           113928	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      114132	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               114360	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   114492	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           114672	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           114852	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      115032	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        115212	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   115440	/*Device.BulkData.Profile.i*/
#define RDM_OID_BULK_DATA_PROF_PARAM             115812	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_MQTT                             115872	/*Device.MQTT*/
#define RDM_OID_MQTT_CAPABILITY                  115956	/*Device.MQTT.Capability*/
#define RDM_OID_MQTT_CLIENT                      116040	/*Device.MQTT.Client.i*/
#define RDM_OID_MQTT_CLIENT_PUB_CONF             117012	/*Device.MQTT.Client.i.X_ZYXEL_Publish_Config.i*/
#define RDM_OID_MQTT_CLIENT_STATS                117144	/*Device.MQTT.Client.i.Stats*/
#define RDM_OID_ROM_CONVERT                      117396	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         117456	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     117732	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     117768	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   117996	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        118176	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   118236	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       118512	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       119004	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           119256	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     119388	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        119616	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            119700	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        120120	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       120348	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      120456	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_ZY_HOST_NAME_REPLACE             120588	/*Device.X_ZYXEL_EXT.HostNameReplace*/
#define RDM_OID_PPTP_CFG                         120648	/*Device.X_ZYXEL_EXT.X_ZYXEL_PPTP_Config*/
#define RDM_OID_EOGRE_CFG                        120948	/*Device.X_ZYXEL_EXT.X_ZYXEL_EoGRE_Config*/
#define RDM_OID_LAN_DEV                          121128	/*Device.X_ZYXEL_EXT.LANDevice.i*/
#define RDM_OID_ZY_IGMP                          121236	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          121728	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        121884	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           121992	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       122412	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    122520	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            122676	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    123432	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         123540	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            123648	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     123756	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     123912	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     123996	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   124080	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   124212	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   124296	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             124380	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        124440	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         124524	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            124824	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      124932	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         125208	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           125340	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  125448	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_REMO_MGMT_IP_PASS_THRU           125580	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough*/
#define RDM_OID_REMO_SRV_IP_PASS_THRU            125664	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN_IP_PASS_THRU 125940	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV_IP_PASS_THRU         126048	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN_IP_PASS_THRU 126324	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN_IP_PASS_THRU 126456	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN_IP_PASS_THRU     126564	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      126696	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   126756	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      127008	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_GPON_INFO                        127236	/*Device.X_ZYXEL_GPON_Info*/
#define RDM_OID_LOG_SETTING                      127440	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     127692	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     127800	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 127980	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      128112	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       128244	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 128424	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 128580	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            128640	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                128700	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            129168	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        129324	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  130008	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_W_W_A_N_CELLULAR_CPE_WAN_BACKUP_CONFIG 130236	/*Device.X_ZYXEL_WWAN_BACKUP.CellularCpeWanBackupConfig*/
#define RDM_OID_ZY_SAMBA                         130656	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     130740	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                130992	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 131388	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     131568	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     131844	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               131904	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       132036	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             132168	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              132204	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              132912	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              133380	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       133512	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         133620	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        133728	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               133860	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           134016	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             134100	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          134256	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           134340	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         134424	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             134460	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          134664	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            134820	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            134904	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           135060	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        135240	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         135300	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              135528	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         135588	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      135720	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            135780	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      135840	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   135900	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 136008	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 136092	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          136224	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             136332	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               136608	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_ONLINE_MODULE_UPGRADE            136908	/*Device.X_ZYXEL_Online_Module_Upgrade*/
#define RDM_OID_LANDING_PAGE                     137184	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       137268	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   137664	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    137820	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              137928	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_RESET_ADMIN                   137988	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_OI_WIZARD                        138048	/*Device.X_ZYXEL_OiWizard*/
#define RDM_OID_ZY_DATA_USAGE                    138252	/*Device.X_ZYXEL_DataUsage*/
#define RDM_OID_ZY_DATA_USAGE_LAN                138312	/*Device.X_ZYXEL_DataUsage.Lan.i*/
#define RDM_OID_ZY_DATA_USAGE_WAN                138420	/*Device.X_ZYXEL_DataUsage.Wan.i*/
#define RDM_OID_IPERF                            138528	/*Device.X_TELECOMITALIA_IT_Iperf*/

#define RDM_OID_MAX                   138660     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
